export const MEMORY_GUIDE = [
  { letter: 'A', morse: '.-', phrase: 'about' },
  { letter: 'B', morse: '-...', phrase: 'BOOK is very good' },
  { letter: 'C', morse: '-.-.', phrase: 'COde MOrse COde' },
  { letter: 'D', morse: '-..', phrase: 'DOg it up' },
  { letter: 'E', morse: '.', phrase: 'eh' },
  { letter: 'F', morse: '..-.', phrase: 'did it FAIL' },
  { letter: 'G', morse: '--.', phrase: 'GOOD GOd' },
  { letter: 'H', morse: '....', phrase: 'hi hi hi hi' },
  { letter: 'I', morse: '..', phrase: 'i it' },
  { letter: 'J', morse: '.---', phrase: 'a JOLLY GOOD WORD' },
  { letter: 'K', morse: '-.-', phrase: 'KICK a CAN' },
  { letter: 'L', morse: '.-..', phrase: 'a LOVE ly lily' },
  { letter: 'M', morse: '--', phrase: 'MORE MORE' },
  { letter: 'N', morse: '-.', phrase: 'NO sir' },
  { letter: 'O', morse: '---', phrase: 'OH MY GOD' },
  { letter: 'P', morse: '.--.', phrase: 'a PLAY GROUND' },
  { letter: 'Q', morse: '--.-', phrase: 'QUEEN MARY CAME' },
  { letter: 'R', morse: '.-.', phrase: 'a RED rose' },
  { letter: 'S', morse: '...', phrase: 'sis sis sis' },
  { letter: 'T', morse: '-', phrase: 'TALL' },
  { letter: 'U', morse: '..-', phrase: 'you you RIGHT' },
  { letter: 'V', morse: '...-', phrase: 'vie vie TORY' },
  { letter: 'W', morse: '.--', phrase: 'a WORD WORD' },
  { letter: 'X', morse: '-..-', phrase: 'EXTRA HEAVY LOAD' },
  { letter: 'Y', morse: '-.--', phrase: 'YOUNG ONES ALWAYS WIN' },
  { letter: 'Z', morse: '--..', phrase: 'ZINC ZINC it it' }
];